### DISCUSSION TITLE
Build on github

### DISCUSSION THREAD

**Discussion by noahfraiture** [TheDan64/inkwell#537] [Q&A]
Hello, 

I'm discovering github actions and I try to test my code with it. Currently my rust.yml is the following : 
```
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
```

But I don't have llvm on the image and thus the build fail `could not compile llvm-sys` obviously.
What is the best solution ? Should I search for an image with llvm or should I try to install it as a step ? But with what base image then ?

**Comment by mealet** [comment]
You can use LLVM installer from marketplace like this:
```
      - name: LLVM Install
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 18
```

On Ubuntu runner it works fine, but on Mac it also requires `zstd` lib, and Windows requires `libxml2`.
