### ISSUE TITLE
Segmentation fault with build_load

### ISSUE THREAD

**Issue by vishpat** [TheDan64/inkwell#402]
**Describe the Bug**
The build_load API is causing a segmentation fault.

**To Reproduce**
```rust
const MAIN_FUNC_NAME: &str = "main";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let context = Context::create();
    let module = context.create_module("main");
    let builder = context.create_builder();

    let main_func = module.add_function(
        MAIN_FUNC_NAME,
        context.f64_type().fn_type(&[], false),
        None,
    );

    let main_block = context.append_basic_block(main_func, "entry");
    builder.position_at_end(main_block);

    let name = "test";
    let val = context.f64_type().const_float(10.0);

    let ptr = builder.build_alloca(context.f64_type(), name);
                builder.build_store(ptr, val);
    builder.build_store(ptr, val);
    let val2 =  builder.build_load(ptr, name);
    println!("{:?}", val2);
    Ok(())
}
```

**Expected Behavior**
The build_load call should return the store value pointed by the pointer.

**LLVM Version (please complete the following information):**
 - LLVM Version: llvm12-0
 - Inkwell Branch Used: master

**Desktop (please complete the following information):**
 - OS: CentOS 7

**Additional Context**
Cargo toml for the application

```toml
[dependencies]
log = "0.4.17"
env_logger = "0.9.0"
linefeed = "0.6.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"] }
```
