### ISSUE TITLE
`Builder::clear_insertion_position` doesn't reset the internal `PositionState`

### ISSUE THREAD

**Issue by Qwox0** [TheDan64/inkwell#560]
The `Builder::clear_insertion_position` method should reset the `positioned` field to `PositionState::NotSet`. Otherwise, the following example segfaults:

```rust
use inkwell::context::Context;

fn main() {
    let context = Context::create();
    let builder = context.create_builder();
    let module = context.create_module("mod");

    let fn_ty = context.void_type().fn_type(&[], false);
    let fn_val = module.add_function("fn", fn_ty, None);
    let entry = context.append_basic_block(fn_val, "entry");
    builder.position_at_end(entry);
    builder.build_return(None).unwrap();
    builder.clear_insertion_position(); // without this the second assert would fail
    assert!(fn_val.verify(true));

    builder
        .build_alloca(context.i32_type(), "bad_var")
        .expect_err("should fail with BuilderError::UnsetPosition"); // -> Segmentation fault

    assert!(fn_val.verify(true));
}
```
`Cargo.toml`:
```toml
# ...

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", features = [
    "llvm18-0",
] }
```
